import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { Montserrat } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik = Montserrat({ subsets: ['latin'], weight: '100' })


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
